name: Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    types: [ready_for_review, synchronize, opened]

jobs:
  php-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        php: [7.1, 7.2, 7.3, 7.4, 8.0, 8.1]
        laravel: [5.8.*, 6.*, 7.*, 8.*, 9.*]
        os: [ubuntu-latest]
        include:
          - laravel: 9.*
            testbench: 7.*
            database: 7.*
          - laravel: 8.*
            testbench: 6.*
            database: 6.*
          - laravel: 7.*
            testbench: 5.*
            database: 5.*
          - laravel: 6.*
            testbench: 4.*
            database: 4.*
          - laravel: 5.8.*
            testbench: 3.8.*
            database: 3.8.*
        exclude:
          - laravel: 5.8.*
            php: 8.0
          - laravel: 6.*
            php: 7.1
          - laravel: 7.*
            php: 7.1
          - laravel: 8.*
            php: 7.1
          - laravel: 8.*
            php: 7.2
          - laravel: 9.*
            php: 7.1
          - laravel: 9.*
            php: 7.2
          - laravel: 9.*
            php: 7.3
          - laravel: 9.*
            php: 7.4

    name: PHP ${{ matrix.php }} / Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extension: mbstring, pdo, pdo_sqlite
          coverage: none

      - name: Install dependencies
        run: |
          composer require "illuminate/contracts:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "orchestra/database:${{ matrix.database }}" --no-interaction --no-update
          composer install --prefer-dist --no-interaction --no-suggest

      - name: Run tests
        run: vendor/bin/phpunit --exclude-group skipped
